# dev
'%dev':
  quarkus:
    package:
      type: uber-jar
    application:
      name: system
      version: 1.0
    http:
      port: 8000
    swagger-ui:
      enable: false
    smallrye-openapi:
      enable: false
#    rabbitmqclient:
#      virtual-host: jan
#      username: jan
#      password: jan123456
#      addresses:
#        master:
#          hostname: localhost
#          port: 5672
    eureka:
      context-path: ${quarkus.http.root-path:/}
      health-check-url: /info/health
      home-page-url: /
      name: ${quarkus.application.name}
      port: ${quarkus.http.port}
      prefer-ip-address: false
      status-page-url: /info/status
      region: default
      prefer-same-zone: true
      service-url:
        eureka1: http://janyyyy:dev1234@localhost:18089/eureka/
    netty-socketio:
      ## 服务上下文地址，该地址与Nginx负载地址适配 /socket.io
      context: /socket.io
      ## host在本地测试可以设置为localhost或者本机IP，在Linux服务器跑可换成服务器IP
      hostname: 0.0.0.0
      ## netty启动端口
      port: 9999
      ## Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
      ping-interval: 1000
      ## Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
      ping-timeout: 3000
      ## 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
      max-frame-payload-length: 1048576
      ## 设置http交互最大内容长度
      max-http-content-length: 1048576
      ## socket连接数大小（如只监听一个端口boss线程组为1即可）
      boss-threads: 1
      worker-threads: 100
      origin: ":*:"
  # IP 本地解析
  ip:
    local-parsing: true
  parcelReceiveFile:
    path: D:/Download/zip/
  excel:
    template:
      path: D:/Download/template/
  async:
    task:
      error:
        excel:
          url: D:/Download/error/excel/
  avatar:
    url: D:/Download/avatar/
  rsa:
    privateKey: MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEA0vfvyTdGJkdbHkB8mp0f3FE0GYP3AYPaJF7jUd1M0XxFSE2ceK3k2kw20YvQ09NJKk+OMjWQl9WitG9pB6tSCQIDAQABAkA2SimBrWC2/wvauBuYqjCFwLvYiRYqZKThUS3MZlebXJiLB+Ue/gUifAAKIg1avttUZsHBHrop4qfJCwAI0+YRAiEA+W3NK/RaXtnRqmoUUkb59zsZUBLpvZgQPfj1MhyHDz0CIQDYhsAhPJ3mgS64NbUZmGWuuNKp5coY2GIj/zYDMJp6vQIgUueLFXv/eZ1ekgz2Oi67MNCk5jeTF2BurZqNLR3MSmUCIFT3Q6uHMtsB9Eha4u7hS31tj1UWE+D+ADzp59MGnoftAiBeHT7gDMuqeJHPL4b+kC+gzV4FGTfhR9q3tTbklZkD2A==
  bulk:
  authorization:
    permit-patterns: /myWebSocket,/auth/login,/auth/code,/auth/logout,/swagger,/q/,/info/health,/info/status
  mp:
    jwt:
      verify:
        publickey:
          location: publicKey.pem
        issuer: https://yujianyou.com
  jwt:
    duration: 604800

