quarkus:
  redis:
    #      client-type: cluster
    #      hosts: redis://localhost:6371,redis://localhost:6372,redis://localhost:6373,redis://localhost:6374,redis://localhost:6375,redis://localhost:6376
    #      hosts-provider-name: QuoteRedisHostsProvider
    #      password: janyyyy
    #      timeout: 5000
    hosts: redis://localhost:6379/3
    password: dev
    timeout: 5000
    tcp-keep-alive: true
  eureka:
    context-path: ${quarkus.http.root-path:/}
    health-check-url: /info/health
    home-page-url: /
    name: ${quarkus.application.name}
    port: ${quarkus.http.port}
    prefer-ip-address: true
    status-page-url: /info/status
    region: default
    prefer-same-zone: true
    service-url:
      eureka1: http://janyyyy:dev1234@localhost:18089/eureka/

